
#ifndef __EVENTDEFINE_H__
#define __EVENTDEFINE_H__

#include  "./base/Global.h"
#include <list>
#include <vector>

using namespace std;
struct tGameEventDefine;
struct tGameEventData;

 
typedef X_VOID (* EVENT_FUNCTION_HANDLE)(const tGameEventData* pEvent, X_UINT dwOwnerData);

typedef std::list< std::pair<EVENT_FUNCTION_HANDLE, X_UINT> > FUNCTIONHANDLELIST;

struct tGameEventDefine
{
	X_INT			m_nEventIntID;
	string			m_szEventStringID;
	FUNCTIONHANDLELIST	m_FunctionHandleList;
	 
};
 

struct tGameEventData
{
	tGameEventDefine*		m_pEventDef;
	std::vector<string>		m_vArg;

	tGameEventData()
	{
		m_pEventDef	= X_NULL;
		m_vArg.clear();
	}
	bool  operator == (const tGameEventData& EventData)
	{
		if (m_pEventDef->m_nEventIntID == EventData.m_pEventDef->m_nEventIntID)
		{
			std::vector<string> v1 = m_vArg;
			std::vector<string> v2 = EventData.m_vArg;
			sort(v1.begin(),v1.end());
			sort(v2.begin(),v2.end());
			return v1 == v2;
		}
		return false;
	}
};

enum GAME_EVENT_ID
{
	GAME_EVENT_ID_INVALID = -1,
	GAME_EVENT_UPDATAUI_SHOW,
	GAME_EVENT_INIT,	
	GAME_EVENT_LOGIN_SHOW,
	GAME_EVENT_MAINPAGE_SHOW,
	GAME_EVENT_MAINPAGE_UPDATA,

	GAME_EVENT_BATTLE_SHOW,
	GAME_EVENT_ACTIVITIES_SHOW,
	GAME_EVENT_LOGIN_CLOSE,
	GAME_EVENT_SELECTROLE_SHOW,
	GAME_EVENT_LOGO_SHOW,
	GAME_EVENT_BATTLEFIELD_SHOW,
	GAME_EVENT_BATTLEFIELD_CLOSE,
	GAME_EVENT_UPDATA_PACKET,

	GAME_EVENT_RECRUIT_SHOW,
	GAME_EVENT_RECRUIT_UPDATA,

	GAME_EVENT_HEROBOOK_SHOW,
	GAME_EVENT_HEROBOOK_UPDATA,

	GAME_EVENT_SECRETSTORE_SHOW,
	GAME_EVENT_SECRETSTORE_UPDATA,

	GAME_EVENT_RECHARGE_SHOW,
	GAME_EVENT_RECHARGE_UPDATA,

	GAME_EVENT_LOADDISTRIBUTE_SHOW,
	GAME_EVENT_LOADDISTRIBUTE_UPDATA,
	GAME_EVENT_LOADDISTRIBUTE_CLOSE,

	GAME_EVENT_HEROINFO_SHOW,
	GAME_EVENT_HEROINFO_UPDATA,
	GAME_EVENT_HEROINFO_CLOSE,

	GAME_EVENT_HEROFIGHTCHOOSE_SHOW,
	GAME_EVENT_HEROFIGHTCHOOSE_UPDATA,
	GAME_EVENT_HEROFIGHTCHOOSE_CLOSE,

	GAME_EVENT_BAGOWN_SHOW,
	GAME_EVENT_BAGOWN_UPDATA,

	GAME_EVENT_TEAMLIST_SHOW,
	GAME_EVENT_TEAMLIST_UPDATA,

	GAME_EVENT_ACHIEVE_SHOW,
	GAME_EVENT_ACHIEVE_UPDATA,

	GAME_EVENT_TASKINFO_SHOW,
	GAME_EVENT_TASKINFO_UPDATA,

	GAME_EVENT_EQUIPMENTINSPECT_SHOW,
	GAME_EVENT_EQUIPMENTINSPECT_UPDATA,
	GAME_EVENT_EQUIPMENTINSPECT_CLOSE,

	GAME_EVENT_EQUIPMENTALL_SHOW,
	GAME_EVENT_EQUIPMENTALL_UPDATA,

	GAME_EVENT_HEROEVOLVE_SHOW,
	GAME_EVENT_HEROEVOLVE_UPDATA,
	GAME_EVENT_HEROEVOLVE_CLOSE,

	GAME_EVENT_HEROUPGRADE_SHOW,
	GAME_EVENT_HEROUPGRADE_UPDATA,
	GAME_EVENT_HEROUPGRADE_CLOSE,

	GAME_EVENT_SKILLINSPECT_SHOW,
	GAME_EVENT_SKILLINSPECT_UPDATA,
	GAME_EVENT_SKILLINSPECT_CLOSE,

	GAME_EVENT_SETTING_SHOW,
	GAME_EVENT_SETTING_UPDATA,

	GAME_EVENT_CHATMESSAGE_SHOW,
	GAME_EVENT_CHATMESSAGE_UPDATA,

	GAME_EVENT_LEVELLIST_SHOW,
	GAME_EVENT_LEVELLIST_UPDATA,

	GAME_EVENT_MESSAGE_SHOW,
	GAME_EVENT_MESSAGE_UPDATA,

	GAME_EVENT_RANKLIST_SHOW,
	GAME_EVENT_RANKLIST_UPDATA,

	GAME_EVENT_ALTAR_SHOW,
	GAME_EVENT_ALTAR_UPDATA,
	GAME_EVENT_ALTAR_CLOSE,
	GAME_EVENT_TIP_SHOW,
	GAME_EVENT_TIP_UPDATA,
	GAME_EVENT_FIGHTRESULT_SHOW,
	GAME_EVENT_FIGHTRESULT_UPDATA,
	GAME_EVENT_FIGHTRESULT_CLOSE,


	GAME_EVENT_SKILLUPGRADE_EQU_SHOW,
	GAME_EVENT_SKILLUPGRADE_EQU_UPDATA,
	GAME_EVENT_SKILLUPGRADE_EQU_CLOSE,

	GAME_EVENT_SKILLUPGRADE_STATUS_SUCCESS,

	GAME_EVENT_HERO_EQUI_SHOW,
	GAME_EVENT_HERO_EQUI_UPDATA,
	GAME_EVENT_HERO_EQUI_CLOSE,


	GAME_EVENT_TIPITEM_SHOW,
	GAME_EVENT_TIPITEM_CLOSE,

	GAME_EVENT_EQUIPMENT_SELL_SHOW,
	GAME_EVENT_EQUIPMENT_SELL_UPDATA,
	GAME_EVENT_EQUIPMENT_SELL_CLOSE,


	GAME_EVENT_USER_INFO_SHOW,
	GAME_EVENT_USER_INFO_UPDATA,
	GAME_EVENT_USER_INFO_CLOSE,
	GAME_EVENT_USER_INFO_BUY_ACTION,

	GAME_EVENT_CHEESE_SHOW,
	GAME_EVENT_CHEESE_UPDATA,
	GAME_EVENT_CHEESE_CLOSE,

	GAME_EVENT_NOTICE_UPDATA,

	GAME_EVNET_LVL_UPGRADE_SHOW,
	GAME_EVNET_LVL_UPGRADE_UPDATA,
	GAME_EVNET_LVL_UPGRADE_CLOSE,
	GAME_EVNET_GUIDE_SHOW,


	GAME_EVNET_USER_LOGIN_SHOW,
	GAME_EVNET_USER_LOGIN_UPDATA,
	GAME_EVNET_USER_LOGIN_CLOSE,
	GAME_EVNET_USER_REG_FAILED,
	GAME_EVNET_USER_REG_SUCCESS,
	GAME_EVNET_USER_CHECK_FAILED,
	GAME_EVNET_USER_CHECK_SUCCESS,

	GAME_EVENT_BASE_ACTIVITY_SHOW,
	GAME_EVENT_BASE_ACTIVITY_UPDATA,
	GAME_EVENT_BASE_ACTIVITY_CLOSE,

	GAME_EVENT_HEROWOODFIGHTCHOOSE_SHOW,
	GAME_EVENT_HEROWOODFIGHTCHOOSE_UPDATA,
	GAME_EVENT_HEROWOODFIGHTCHOOSE_CLOSE,
	GAME_EVENT_OTHERHEROINFO_SHOW,
	GAME_EVENT_OTHERHEROINFO_UPDATA,
	GAME_EVENT_OTHERHEROINFO_CLOSE,

	GAME_EVENT_BLOODBATTLE_SHOW,
	GAME_EVENT_BLOODBATTLE_UPDATA,
	GAME_EVENT_BLOODBATTLE_CLOSE,

	GAME_EVNET_LVL_ESCORTWOOD_SHOW,
	GAME_EVNET_LVL_ESCORTWOOD_UPDATA,
	GAME_EVNET_LVL_ESCORTWOOD_CLOSE,

	GAME_EVNET_WOODSHIZHE_SHOW,
	GAME_EVNET_WOODSHIZHE_UPDATA,
	GAME_EVNET_WOODSHIZHE_CLOSE,
	GAME_EVENT_PLACARD_SHOW,
	GAME_EVENT_GIFTDETAIL_SHOW,


	GAME_EVENT_SHAKE_SHOW,
	GAME_EVENT_SHAKE_UPDATA,
	EVENT_NUM,										 
 
};
 
#endif


